// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/write-version.js

export const APP_VERSION = "1.1.5";
export const APP_GIT_SHA = "";
export const APP_BUILD_TIME = "2026-04-21T12:58:05.198Z";
