// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/write-version.js

export const APP_VERSION = "1.2.0";
export const APP_GIT_SHA = "";
export const APP_BUILD_TIME = "2026-09-09T10:44:29.806Z";
