/* eslint-disable no-console */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

function safeReadJson(p) {
  try {
    return JSON.parse(fs.readFileSync(p, "utf8"));
  } catch {
    return null;
  }
}

function safeGitSha() {
  try {
    // Works when .git is available. If not (e.g. zip deploy), returns empty.
    return String(execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] }))
      .trim()
      .slice(0, 12);
  } catch {
    return "";
  }
}

function main() {
  const root = path.resolve(__dirname, "..");
  const pkgPath = path.join(root, "package.json");
  const pkg = safeReadJson(pkgPath) || {};
  const version = String(pkg.version || "0.0.0");

  const gitSha = safeGitSha();
  const buildTime = new Date().toISOString();

  const outDir = path.join(root, "src");
  const outPath = path.join(outDir, "appVersion.js");
  const publicDir = path.join(root, "public");
  const publicVersionPath = path.join(publicDir, "version.json");

  if (!fs.existsSync(outDir)) {
    console.error("ERROR: src/ folder not found. Expected:", outDir);
    process.exit(1);
  }
  if (!fs.existsSync(publicDir)) {
    console.error("ERROR: public/ folder not found. Expected:", publicDir);
    process.exit(1);
  }

  const contents =
    `// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.\n` +
    `// Generated by scripts/write-version.js\n` +
    `\n` +
    `export const APP_VERSION = "${version}";\n` +
    `export const APP_GIT_SHA = "${gitSha}";\n` +
    `export const APP_BUILD_TIME = "${buildTime}";\n`;

  fs.writeFileSync(outPath, contents, "utf8");
  console.log("Wrote version file:", outPath);

  const publicVersion = {
    version,
    gitSha,
    buildTime
  };
  fs.writeFileSync(publicVersionPath, `${JSON.stringify(publicVersion, null, 2)}\n`, "utf8");
  console.log("Wrote public version file:", publicVersionPath);
}

main();
